### ISSUE TITLE
Can't parse some valid YML files

### ISSUE THREAD

**Issue by reiz** [ruby/syck#21]
We are using this Gem for [VersionEye](https://www.versioneye.com/) in this [git repository](https://github.com/versioneye/versioneye-security). We call it like this: 

```
YAML.load_file filepath
```

See [here](https://github.com/versioneye/versioneye-security/blob/master/lib/versioneye/php_sensiolabs_crawler.rb#L103). 

Most of the time it works fine but sometimes it throws this exception: 

```
ArgumentError: syntax error on line 6, col 37: `        versions: ['>=1.7.0','<1.7.9']'
        from /usr/local/bundle/gems/syck-1.2.0/lib/syck.rb:145:in `load'
        from /usr/local/bundle/gems/syck-1.2.0/lib/syck.rb:145:in `load'
        from /usr/local/bundle/gems/syck-1.2.0/lib/syck.rb:156:in `block in load_file'
        from /usr/local/bundle/gems/syck-1.2.0/lib/syck.rb:155:in `open'
        from /usr/local/bundle/gems/syck-1.2.0/lib/syck.rb:155:in `load_file'
        from (irb):10
        from /usr/local/bin/irb:11:in `<main>'
```

For example for a file with this content: 

```
title:      Potential XSS vector in Zend_Filter_StripTags when comments allowed
link:       http://framework.zend.com/security/advisory/ZF2010-03
cve:        ~
branches:
    1.7.x:
        time:     2010-01-08 17:31:22
        versions: ['>=1.7.0','<1.7.9']
    1.8.x:
        time:     2010-01-08 17:31:22
        versions: ['>=1.8.0','<1.8.5']
    1.9.x:
        time:     2010-01-08 17:31:22
        versions: ['>=1.9.0','<1.9.7']
```

According to [YamlLint](http://www.yamllint.com/) it is valid Yaml syntax, but somehow Syck can not process it. 

Please help. Any ideas? Any workarounds?

**Comment by reiz** [comment]
@hsbt Your feedback is highly appreciated.

**Comment by hsbt** [comment]
What version of yaml spec on yamllint? Syck is only support yaml 1.0, maybe.

**Comment by reiz** [comment]
Hi @hsbt Somehow Syck can't handle an array without white spaces. Every time I had an array like this `['1.2','3.4']` it caused an error. The same array with a white space after the comma works `['1.2', '3.4']`. After adding this line: 

```
Syck.load content.gsub("','", "', '")
```

I can parse all Yaml files.
