### ISSUE TITLE
Gemfile.lock has been delivered with 1.4.0

### ISSUE THREAD

**Issue by schmijos** [ruby/syck#28]
The publisher has built the gem with his/her `Gemfile.lock`. Not sure what the implications are.

**Comment by hsbt** [comment]
I'm not sure what's your problem. Can you elaborate on it?

**Comment by schmijos** [comment]
I don't have a specific problem. I just got suspicious when I compared 1.3.0 with 1.4.0.

![image](https://user-images.githubusercontent.com/245443/65683723-5048b280-e05e-11e9-967a-921655d1818f.png)

**Comment by hsbt** [comment]
Got it. Because it caused by https://github.com/ruby/syck/blob/master/syck.gemspec#L15
