### ISSUE TITLE
JRuby support

### ISSUE THREAD

**Issue by Gawyn** [ruby/syck#31]
Is there a plan for Syck to support JRuby? If not, is there a way for JRuby to read a YAML created by Syck? In most of cases the Syck-generated YML will be readable by Psych, but that's not the case all the time, like for example:

```
irb(main):012:0> h = {a: ',foo'}
=> {:a=>",foo"}
irb(main):013:0> Psych.load(Syck.dump(h))
[...]
Psych::SyntaxError ((<unknown>): did not find expected node content while parsing a block node at line 2 column 5)
```

Thank you!

**Comment by hsbt** [comment]
Unfortunately, There is no plan to support JRuby.

@headius Do you have any idea about this issue?

**Comment by headius** [comment]
JRuby used to support syck using the "yecht" implementation by @olabini. The code is still out there and could be adapted to work with JRuby 9.x.

https://github.com/jruby/yecht
